### ISSUE TITLE
rails 3.2

### ISSUE THREAD

**Issue by jackchang** [tomichj/signature-pad-rails#3]
Does it support rails 3.2?

**Comment by tomichj** [comment]
Hello Jack,

Thus far, the minimum supported version was rails 4.0. Given your request, I fired up a rails 3 app and tested the gem, it appears fully functional. I updated the gem and pushed to github and rubygems.org to support rails 3. It's obviously not well tested. If you give it a try and find any problems, please open a bug or fork and make a pull request. Thanks!

**Comment by jackchang** [comment]
Justin,
Many thanks, will test it out.

Regards,

Jack
