### ISSUE TITLE
Does this gem require Flash in the browser?

### ISSUE THREAD

**Issue by dchersey** [tomichj/signature-pad-rails#5]
Hello, and thank you for maintaining this gem!

I see there is a dependency on FlashCanvas, which replicates HTML5 Canvas functionality in IE using Flash. 

Does this mean that if the browser supports HTML5, there is no dependency on flash?

Thanks!

**Comment by tomichj** [comment]
Hello! You are correct; signature pad depends on HTML5's <canvas> element, not on Flash. If your browser supports <canvas>, Flash is not required.
